# Generated by Django 5.2.9 on 2025-12-25 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentalHealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('employment_status', models.CharField(max_length=50)),
                ('work_environment', models.CharField(max_length=20)),
                ('mental_health_history', models.CharField(max_length=10)),
                ('seeks_treatment', models.CharField(max_length=10)),
                ('stress_level', models.IntegerField()),
                ('sleep_hours', models.FloatField()),
                ('physical_activity_days', models.IntegerField()),
                ('depression_score', models.IntegerField()),
                ('anxiety_score', models.IntegerField()),
                ('social_support_score', models.IntegerField()),
                ('productivity_score', models.FloatField()),
                ('predicted_risk', models.CharField(max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
